//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityServiceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buildings
    {
        public Buildings()
        {
            this.Requests = new HashSet<Requests>();
            this.Residents = new HashSet<Residents>();
        }
    
        public int BuildingID { get; set; }
        public string AddressLine { get; set; }
        public Nullable<System.DateTime> ManagementStart { get; set; }
        public Nullable<int> FloorsCount { get; set; }
        public Nullable<int> ApartmentsCount { get; set; }
        public Nullable<int> BuildYear { get; set; }
        public Nullable<decimal> TotalArea { get; set; }
    
        public virtual ICollection<Requests> Requests { get; set; }
        public virtual ICollection<Residents> Residents { get; set; }
    }
}
