//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityServiceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        public int RequestID { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public int BuildingID { get; set; }
        public string ApartmentNumber { get; set; }
        public Nullable<int> ResidentID { get; set; }
        public string Description { get; set; }
        public Nullable<int> ExecutorID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
    
        public virtual Buildings Buildings { get; set; }
        public virtual Users Users { get; set; }
        public virtual Residents Residents { get; set; }
        public virtual Statuses Statuses { get; set; }
    }
}
