//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityServiceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Residents
    {
        public Residents()
        {
            this.Requests = new HashSet<Requests>();
        }
    
        public int ResidentID { get; set; }
        public string FullName { get; set; }
        public string Phone { get; set; }
        public Nullable<int> BuildingID { get; set; }
        public string ApartmentNumber { get; set; }
    
        public virtual Buildings Buildings { get; set; }
        public virtual ICollection<Requests> Requests { get; set; }
    }
}
